(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
// shim for using process in browser

var process = module.exports = {};
var queue = [];
var draining = false;
var currentQueue;
var queueIndex = -1;

function cleanUpNextTick() {
    draining = false;
    if (currentQueue.length) {
        queue = currentQueue.concat(queue);
    } else {
        queueIndex = -1;
    }
    if (queue.length) {
        drainQueue();
    }
}

function drainQueue() {
    if (draining) {
        return;
    }
    var timeout = setTimeout(cleanUpNextTick);
    draining = true;

    var len = queue.length;
    while(len) {
        currentQueue = queue;
        queue = [];
        while (++queueIndex < len) {
            currentQueue[queueIndex].run();
        }
        queueIndex = -1;
        len = queue.length;
    }
    currentQueue = null;
    draining = false;
    clearTimeout(timeout);
}

process.nextTick = function (fun) {
    var args = new Array(arguments.length - 1);
    if (arguments.length > 1) {
        for (var i = 1; i < arguments.length; i++) {
            args[i - 1] = arguments[i];
        }
    }
    queue.push(new Item(fun, args));
    if (!draining) {
        setTimeout(drainQueue, 0);
    }
};

// v8 likes predictible objects
function Item(fun, array) {
    this.fun = fun;
    this.array = array;
}
Item.prototype.run = function () {
    this.fun.apply(null, this.array);
};
process.title = 'browser';
process.browser = true;
process.env = {};
process.argv = [];
process.version = ''; // empty string to avoid regexp issues
process.versions = {};

function noop() {}

process.on = noop;
process.addListener = noop;
process.once = noop;
process.off = noop;
process.removeListener = noop;
process.removeAllListeners = noop;
process.emit = noop;

process.binding = function (name) {
    throw new Error('process.binding is not supported');
};

// TODO(shtylman)
process.cwd = function () { return '/' };
process.chdir = function (dir) {
    throw new Error('process.chdir is not supported');
};
process.umask = function() { return 0; };

},{}],2:[function(require,module,exports){
// Generated by LiveScript 1.4.0
(function(){
  module.exports = {
    SERVER: {
      url: 'ws://localhost:8000/ws',
      realm: 'riichi'
    },
    PREFIX: 'io.github.summivox.riichi',
    PAI_H: 1.3,
    PAI_PATH: "img/pai"
  };
}).call(this);

},{}],3:[function(require,module,exports){
// Generated by LiveScript 1.4.0
(function(){
  var ref$, PAI_H, PAI_PATH, $, $new, $class, $render, qS, qSA, $HTML, Pai, PaiRow, Sutehai, out$ = typeof exports != 'undefined' && exports || this;
  ref$ = require('./conf'), PAI_H = ref$.PAI_H, PAI_PATH = ref$.PAI_PATH;
  ref$ = window.React, $ = ref$.DOM, $new = ref$.createElement, $class = ref$.createClass, $render = ref$.render;
  qS = function(it){
    return document.querySelector(it);
  };
  qSA = function(it){
    return document.querySelectorAll(it);
  };
  $HTML = function(it){
    return {
      dangerouslySetInnerHTML: {
        __html: it
      }
    };
  };
  out$.Pai = Pai = $class({
    displayName: 'Pai',
    render: function(){
      var ref$, pai, x, y, rot, className, transform;
      ref$ = this.props, pai = ref$.pai, x = ref$.x, y = ref$.y, rot = ref$.rot, className = ref$.className;
      className == null && (className = '');
      className += ' pai';
      if (!/^\d[mpsz]$/.test(pai)) {
        return null;
      }
      switch (rot) {
      case -1:
        transform = "rotate(-90)";
        break;
      case 0:
        transform = "translate(0, -" + PAI_H + ")";
        break;
      case +1:
        transform = "translate(" + PAI_H + ", -1) rotate(+90)";
      }
      return $['g'](importAll$({
        transform: "translate(" + x + " " + y + ")",
        className: className
      }, $HTML("<image xlink:href=\"" + PAI_PATH + "/" + pai + ".svg\"\n  width=\"1\" height=\"" + PAI_H + "\" preserveAspectRatio=\"xMidYMid slice\"\n  transform=\"" + transform + "\"/>")));
    }
  });
  out$.PaiRow = PaiRow = $class({
    displayName: 'PaiRow',
    render: function(){
      var xNext, ref$, right, x, y;
      xNext = 0;
      ref$ = this.props, right = ref$.right, x = ref$.x, y = ref$.y;
      return $['g']({
        transform: "translate(" + x + " " + y + ")"
      }, this.props.list.map(function(arg$, i){
        var pai, pos, space, className, x, y, rot;
        pai = arg$.pai, pos = arg$.pos, space = arg$.space, className = arg$.className;
        switch (pos) {
        case 'l':
        case 'r':
          x = right ? -xNext - PAI_H : xNext;
          y = 0;
          rot = pos === 'l'
            ? -1
            : +1;
          xNext += PAI_H;
          break;
        case 'L':
        case 'R':
          x = right
            ? -xNext
            : xNext - PAI_H;
          y = -1;
          rot = pos === 'L'
            ? -1
            : +1;
          break;
        default:
          x = right ? -xNext - 1 : xNext;
          y = 0;
          rot = 0;
          xNext++;
        }
        if (space) {
          xNext += space;
        }
        return $new(Pai, {
          pai: pai,
          x: x,
          y: y,
          rot: rot,
          className: className != null ? className : '',
          key: i
        });
      }));
    }
  });
  out$.Sutehai = Sutehai = $class({
    displayName: 'Sutehai',
    render: function(){
      var rows, row, ref$, x, y, maxCol, maxRow, sutehai, showFuuro, i$, len$, i, pai, fuuroPlayer, tsumokiri, riichi, className, pos;
      rows = [];
      row = [];
      ref$ = this.props, x = ref$.x, y = ref$.y, maxCol = ref$.maxCol, maxRow = ref$.maxRow, sutehai = ref$.sutehai, showFuuro = ref$.showFuuro;
      for (i$ = 0, len$ = sutehai.length; i$ < len$; ++i$) {
        i = i$;
        ref$ = sutehai[i$], pai = ref$.pai, fuuroPlayer = ref$.fuuroPlayer, tsumokiri = ref$.tsumokiri, riichi = ref$.riichi;
        className = '';
        if (fuuroPlayer != null && !showFuuro) {
          continue;
        }
        if (tsumokiri) {
          className += ' pai-tsumokiri';
        }
        if (riichi) {
          className += ' pai-riichi';
          pos = 'l';
        } else {
          pos = 'u';
        }
        if (row.push({
          pai: pai,
          pos: pos,
          className: className
        }) === maxCol && rows.length <= maxRow - 2) {
          rows.push(row);
          row = [];
        }
      }
      if (row.length) {
        rows.push(row);
      }
      return $['g']({}, rows.map(function(row, i){
        return $new(PaiRow, {
          list: row,
          x: x,
          y: y + (i + 1) * PAI_H,
          right: false,
          key: i
        });
      }));
    }
  });
  out$.rowFromFuuro = rowFromFuuro;
  function rowFromFuuro(fuuro, player){
    var ret, i$, len$, f, own, other, dP;
    ret = [];
    for (i$ = 0, len$ = fuuro.length; i$ < len$; ++i$) {
      f = fuuro[i$];
      own = f.ownPai.sort();
      other = f.otherPai;
      dP = (f.otherPlayer - player + 4) % 4;
      switch (f.type.toString().toLowerCase()) {
      case 'shuntsu':
      case 'minko':
        if (dP === 1) {
          ret.push({
            pai: other,
            pos: 'r'
          });
        }
        ret.push({
          pai: own[1],
          pos: 'u'
        });
        if (dP === 2) {
          ret.push({
            pai: other,
            pos: 'l'
          });
        }
        ret.push({
          pai: own[0],
          pos: 'u'
        });
        if (dP === 3) {
          ret.push({
            pai: other,
            pos: 'l'
          });
        }
        break;
      case 'daiminkan':
        if (dP === 1) {
          ret.push({
            pai: other,
            pos: 'r'
          });
        }
        ret.push({
          pai: own[2],
          pos: 'u'
        });
        ret.push({
          pai: own[1],
          pos: 'u'
        });
        if (dP === 2) {
          ret.push({
            pai: other,
            pos: 'l'
          });
        }
        ret.push({
          pai: own[0],
          pos: 'u'
        });
        if (dP === 3) {
          ret.push({
            pai: other,
            pos: 'l'
          });
        }
        break;
      case 'kakan':
        if (dP === 1) {
          ret.push({
            pai: other,
            pos: 'r'
          });
          ret.push({
            pai: f.kakanPai,
            pos: 'R'
          });
        }
        ret.push({
          pai: own[1],
          pos: 'u'
        });
        if (dP === 2) {
          ret.push({
            pai: other,
            pos: 'l'
          });
          ret.push({
            pai: f.kakanPai,
            pos: 'L'
          });
        }
        ret.push({
          pai: own[0],
          pos: 'u'
        });
        if (dP === 3) {
          ret.push({
            pai: other,
            pos: 'l'
          });
          ret.push({
            pai: f.kakanPai,
            pos: 'L'
          });
        }
        break;
      case 'ankan':
        ret.push({
          pai: '8z',
          pos: 'u'
        });
        ret.push({
          pai: own[1],
          pos: 'u'
        });
        ret.push({
          pai: own[0],
          pos: 'u'
        });
        ret.push({
          pai: '8z',
          pos: 'u'
        });
        break;
      default:
        throw Error("wtf type " + f.type);
      }
    }
    return ret;
  }
  out$.rowFromJuntehai = rowFromJuntehai;
  function rowFromJuntehai(juntehai, tsumo){
    var ret;
    ret = juntehai.map(function(it){
      return {
        pai: it,
        pos: 'u',
        space: 0
      };
    });
    if (tsumo) {
      ret[ret.length - 1].space = 1 / 6;
      ret.push({
        pai: tsumo,
        pos: 'u',
        space: 0
      });
    }
    return ret;
  }
  out$.rowBack = rowBack;
  function rowBack(n, tsumo){
    var ret, res$, i$, i;
    res$ = [];
    for (i$ = 0; i$ < n; ++i$) {
      i = i$;
      res$.push({
        pai: '8z',
        pos: 'u',
        space: 0
      });
    }
    ret = res$;
    if (tsumo) {
      ret[ret.length - 1].space = 1 / 6;
      ret.push({
        pai: '8z',
        pos: 'u',
        space: 0
      });
    }
    return ret;
  }
  function importAll$(obj, src){
    for (var key in src) obj[key] = src[key];
    return obj;
  }
}).call(this);

},{"./conf":2}],4:[function(require,module,exports){
// Generated by LiveScript 1.4.0
(function(){
  var entityMap, out$ = typeof exports != 'undefined' && exports || this;
  out$.utf8_to_b64 = utf8_to_b64;
  function utf8_to_b64(it){
    return window.btoa(unescape(encodeURIComponent(it)));
  }
  out$.b64_to_utf8 = b64_to_utf8;
  function b64_to_utf8(it){
    return decodeURIComponent(escape(window.atob(it)));
  }
  out$.getDataURI = getDataURI;
  function getDataURI(it){
    return 'data:text/html;base64,' + utf8_to_b64(it);
  }
  entityMap = {
    "&": "&amp;",
    "<": "&lt;",
    ">": "&gt;",
    '"': '&quot;',
    "'": '&#39;',
    "/": '&#x2F;'
  };
  out$.escapeHTML = escapeHTML;
  function escapeHTML(it){
    return String(it).replace(/[&<>"'\/]/g, function(it){
      return entityMap[it];
    });
  }
}).call(this);

},{}],5:[function(require,module,exports){
(function (process){
// Generated by LiveScript 1.4.0
(function(){
  var escapeHTML, ref$, SERVER, PREFIX, ui, qS, qSA, svg, con, debugStr, debug, gameId, G, playerName, playerToken, playerSeat, playerNames, subscription, conn, S;
  escapeHTML = require('./util').escapeHTML;
  ref$ = require('./conf'), SERVER = ref$.SERVER, PREFIX = ref$.PREFIX;
  ui = require('./ui');
  qS = function(it){
    return document.querySelector(it);
  };
  qSA = function(it){
    return document.querySelectorAll(it);
  };
  svg = qS('#main');
  con = qS('#con');
  debugStr = con.innerHTML;
  debug = function(it){
    con.innerHTML = debugStr += escapeHTML(it) + '\n';
  };
  gameId = null;
  G = null;
  playerName = null;
  playerToken = null;
  playerSeat = null;
  playerNames = null;
  (function(){
    var s, j, gameId, playerNames, playerSeat, playerToken, e;
    try {
      s = document.location.hash.substr(1);
      j = JSON.parse(decodeURIComponent(s));
      gameId = j.gameId, playerNames = j.playerNames, playerSeat = j.playerSeat, playerToken = j.playerToken;
    } catch (e$) {
      e = e$;
      debug("invalid game URL");
      throw e;
    }
  })();
  subscription = null;
  function subscribe(){
    return subscription = S.subscribe(G, onGameEvent);
  }
  function unSubscribe(){
    if (subscription) {
      return S.unsubscribe(subscription);
    }
  }
  conn = new autobahn.Connection(SERVER);
  S = null;
  conn.onopen = onOpen;
  conn.onclose = onClose;
  process.nextTick(function(){
    debug("connecting to " + SERVER.url + " ...");
    return conn.open();
  });
  function onOpen(){
    debug("connected");
    return S = conn.session;
  }
  function onClose(reason, details){
    debug("lost connection. reason: " + reason);
    console.error(details);
    return S = null;
  }
  function onGameEvent(args, kwargs){
    var type, details;
    type = args[0], details = args[1];
    throw Error('unimplemented');
  }
}).call(this);

}).call(this,require('_process'))

},{"./conf":2,"./ui":3,"./util":4,"_process":1}]},{},[5])
//# sourceMappingURL=data:application/json;charset:utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbImM6L1VzZXJzL1lpbiBaaG9uZy9BcHBEYXRhL1JvYW1pbmcvbnBtL25vZGVfbW9kdWxlcy9icm93c2VyaWZ5L25vZGVfbW9kdWxlcy9icm93c2VyLXBhY2svX3ByZWx1ZGUuanMiLCJjOi9Vc2Vycy9ZaW4gWmhvbmcvQXBwRGF0YS9Sb2FtaW5nL25wbS9ub2RlX21vZHVsZXMvYnJvd3NlcmlmeS9ub2RlX21vZHVsZXMvcHJvY2Vzcy9icm93c2VyLmpzIiwiY29uZi5qcyIsInVpLmpzIiwidXRpbC5qcyIsImdhbWUuanMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBQUE7QUNBQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTs7QUMxRkE7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7O0FDWkE7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7O0FDcFVBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBOzs7QUM5QkE7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBIiwiZmlsZSI6ImdlbmVyYXRlZC5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzQ29udGVudCI6WyIoZnVuY3Rpb24gZSh0LG4scil7ZnVuY3Rpb24gcyhvLHUpe2lmKCFuW29dKXtpZighdFtvXSl7dmFyIGE9dHlwZW9mIHJlcXVpcmU9PVwiZnVuY3Rpb25cIiYmcmVxdWlyZTtpZighdSYmYSlyZXR1cm4gYShvLCEwKTtpZihpKXJldHVybiBpKG8sITApO3ZhciBmPW5ldyBFcnJvcihcIkNhbm5vdCBmaW5kIG1vZHVsZSAnXCIrbytcIidcIik7dGhyb3cgZi5jb2RlPVwiTU9EVUxFX05PVF9GT1VORFwiLGZ9dmFyIGw9bltvXT17ZXhwb3J0czp7fX07dFtvXVswXS5jYWxsKGwuZXhwb3J0cyxmdW5jdGlvbihlKXt2YXIgbj10W29dWzFdW2VdO3JldHVybiBzKG4/bjplKX0sbCxsLmV4cG9ydHMsZSx0LG4scil9cmV0dXJuIG5bb10uZXhwb3J0c312YXIgaT10eXBlb2YgcmVxdWlyZT09XCJmdW5jdGlvblwiJiZyZXF1aXJlO2Zvcih2YXIgbz0wO288ci5sZW5ndGg7bysrKXMocltvXSk7cmV0dXJuIHN9KSIsIi8vIHNoaW0gZm9yIHVzaW5nIHByb2Nlc3MgaW4gYnJvd3NlclxuXG52YXIgcHJvY2VzcyA9IG1vZHVsZS5leHBvcnRzID0ge307XG52YXIgcXVldWUgPSBbXTtcbnZhciBkcmFpbmluZyA9IGZhbHNlO1xudmFyIGN1cnJlbnRRdWV1ZTtcbnZhciBxdWV1ZUluZGV4ID0gLTE7XG5cbmZ1bmN0aW9uIGNsZWFuVXBOZXh0VGljaygpIHtcbiAgICBkcmFpbmluZyA9IGZhbHNlO1xuICAgIGlmIChjdXJyZW50UXVldWUubGVuZ3RoKSB7XG4gICAgICAgIHF1ZXVlID0gY3VycmVudFF1ZXVlLmNvbmNhdChxdWV1ZSk7XG4gICAgfSBlbHNlIHtcbiAgICAgICAgcXVldWVJbmRleCA9IC0xO1xuICAgIH1cbiAgICBpZiAocXVldWUubGVuZ3RoKSB7XG4gICAgICAgIGRyYWluUXVldWUoKTtcbiAgICB9XG59XG5cbmZ1bmN0aW9uIGRyYWluUXVldWUoKSB7XG4gICAgaWYgKGRyYWluaW5nKSB7XG4gICAgICAgIHJldHVybjtcbiAgICB9XG4gICAgdmFyIHRpbWVvdXQgPSBzZXRUaW1lb3V0KGNsZWFuVXBOZXh0VGljayk7XG4gICAgZHJhaW5pbmcgPSB0cnVlO1xuXG4gICAgdmFyIGxlbiA9IHF1ZXVlLmxlbmd0aDtcbiAgICB3aGlsZShsZW4pIHtcbiAgICAgICAgY3VycmVudFF1ZXVlID0gcXVldWU7XG4gICAgICAgIHF1ZXVlID0gW107XG4gICAgICAgIHdoaWxlICgrK3F1ZXVlSW5kZXggPCBsZW4pIHtcbiAgICAgICAgICAgIGN1cnJlbnRRdWV1ZVtxdWV1ZUluZGV4XS5ydW4oKTtcbiAgICAgICAgfVxuICAgICAgICBxdWV1ZUluZGV4ID0gLTE7XG4gICAgICAgIGxlbiA9IHF1ZXVlLmxlbmd0aDtcbiAgICB9XG4gICAgY3VycmVudFF1ZXVlID0gbnVsbDtcbiAgICBkcmFpbmluZyA9IGZhbHNlO1xuICAgIGNsZWFyVGltZW91dCh0aW1lb3V0KTtcbn1cblxucHJvY2Vzcy5uZXh0VGljayA9IGZ1bmN0aW9uIChmdW4pIHtcbiAgICB2YXIgYXJncyA9IG5ldyBBcnJheShhcmd1bWVudHMubGVuZ3RoIC0gMSk7XG4gICAgaWYgKGFyZ3VtZW50cy5sZW5ndGggPiAxKSB7XG4gICAgICAgIGZvciAodmFyIGkgPSAxOyBpIDwgYXJndW1lbnRzLmxlbmd0aDsgaSsrKSB7XG4gICAgICAgICAgICBhcmdzW2kgLSAxXSA9IGFyZ3VtZW50c1tpXTtcbiAgICAgICAgfVxuICAgIH1cbiAgICBxdWV1ZS5wdXNoKG5ldyBJdGVtKGZ1biwgYXJncykpO1xuICAgIGlmICghZHJhaW5pbmcpIHtcbiAgICAgICAgc2V0VGltZW91dChkcmFpblF1ZXVlLCAwKTtcbiAgICB9XG59O1xuXG4vLyB2OCBsaWtlcyBwcmVkaWN0aWJsZSBvYmplY3RzXG5mdW5jdGlvbiBJdGVtKGZ1biwgYXJyYXkpIHtcbiAgICB0aGlzLmZ1biA9IGZ1bjtcbiAgICB0aGlzLmFycmF5ID0gYXJyYXk7XG59XG5JdGVtLnByb3RvdHlwZS5ydW4gPSBmdW5jdGlvbiAoKSB7XG4gICAgdGhpcy5mdW4uYXBwbHkobnVsbCwgdGhpcy5hcnJheSk7XG59O1xucHJvY2Vzcy50aXRsZSA9ICdicm93c2VyJztcbnByb2Nlc3MuYnJvd3NlciA9IHRydWU7XG5wcm9jZXNzLmVudiA9IHt9O1xucHJvY2Vzcy5hcmd2ID0gW107XG5wcm9jZXNzLnZlcnNpb24gPSAnJzsgLy8gZW1wdHkgc3RyaW5nIHRvIGF2b2lkIHJlZ2V4cCBpc3N1ZXNcbnByb2Nlc3MudmVyc2lvbnMgPSB7fTtcblxuZnVuY3Rpb24gbm9vcCgpIHt9XG5cbnByb2Nlc3Mub24gPSBub29wO1xucHJvY2Vzcy5hZGRMaXN0ZW5lciA9IG5vb3A7XG5wcm9jZXNzLm9uY2UgPSBub29wO1xucHJvY2Vzcy5vZmYgPSBub29wO1xucHJvY2Vzcy5yZW1vdmVMaXN0ZW5lciA9IG5vb3A7XG5wcm9jZXNzLnJlbW92ZUFsbExpc3RlbmVycyA9IG5vb3A7XG5wcm9jZXNzLmVtaXQgPSBub29wO1xuXG5wcm9jZXNzLmJpbmRpbmcgPSBmdW5jdGlvbiAobmFtZSkge1xuICAgIHRocm93IG5ldyBFcnJvcigncHJvY2Vzcy5iaW5kaW5nIGlzIG5vdCBzdXBwb3J0ZWQnKTtcbn07XG5cbi8vIFRPRE8oc2h0eWxtYW4pXG5wcm9jZXNzLmN3ZCA9IGZ1bmN0aW9uICgpIHsgcmV0dXJuICcvJyB9O1xucHJvY2Vzcy5jaGRpciA9IGZ1bmN0aW9uIChkaXIpIHtcbiAgICB0aHJvdyBuZXcgRXJyb3IoJ3Byb2Nlc3MuY2hkaXIgaXMgbm90IHN1cHBvcnRlZCcpO1xufTtcbnByb2Nlc3MudW1hc2sgPSBmdW5jdGlvbigpIHsgcmV0dXJuIDA7IH07XG4iLCIvLyBHZW5lcmF0ZWQgYnkgTGl2ZVNjcmlwdCAxLjQuMFxuKGZ1bmN0aW9uKCl7XG4gIG1vZHVsZS5leHBvcnRzID0ge1xuICAgIFNFUlZFUjoge1xuICAgICAgdXJsOiAnd3M6Ly9sb2NhbGhvc3Q6ODAwMC93cycsXG4gICAgICByZWFsbTogJ3JpaWNoaSdcbiAgICB9LFxuICAgIFBSRUZJWDogJ2lvLmdpdGh1Yi5zdW1taXZveC5yaWljaGknLFxuICAgIFBBSV9IOiAxLjMsXG4gICAgUEFJX1BBVEg6IFwiaW1nL3BhaVwiXG4gIH07XG59KS5jYWxsKHRoaXMpO1xuIiwiLy8gR2VuZXJhdGVkIGJ5IExpdmVTY3JpcHQgMS40LjBcbihmdW5jdGlvbigpe1xuICB2YXIgcmVmJCwgUEFJX0gsIFBBSV9QQVRILCAkLCAkbmV3LCAkY2xhc3MsICRyZW5kZXIsIHFTLCBxU0EsICRIVE1MLCBQYWksIFBhaVJvdywgU3V0ZWhhaSwgb3V0JCA9IHR5cGVvZiBleHBvcnRzICE9ICd1bmRlZmluZWQnICYmIGV4cG9ydHMgfHwgdGhpcztcbiAgcmVmJCA9IHJlcXVpcmUoJy4vY29uZicpLCBQQUlfSCA9IHJlZiQuUEFJX0gsIFBBSV9QQVRIID0gcmVmJC5QQUlfUEFUSDtcbiAgcmVmJCA9IHdpbmRvdy5SZWFjdCwgJCA9IHJlZiQuRE9NLCAkbmV3ID0gcmVmJC5jcmVhdGVFbGVtZW50LCAkY2xhc3MgPSByZWYkLmNyZWF0ZUNsYXNzLCAkcmVuZGVyID0gcmVmJC5yZW5kZXI7XG4gIHFTID0gZnVuY3Rpb24oaXQpe1xuICAgIHJldHVybiBkb2N1bWVudC5xdWVyeVNlbGVjdG9yKGl0KTtcbiAgfTtcbiAgcVNBID0gZnVuY3Rpb24oaXQpe1xuICAgIHJldHVybiBkb2N1bWVudC5xdWVyeVNlbGVjdG9yQWxsKGl0KTtcbiAgfTtcbiAgJEhUTUwgPSBmdW5jdGlvbihpdCl7XG4gICAgcmV0dXJuIHtcbiAgICAgIGRhbmdlcm91c2x5U2V0SW5uZXJIVE1MOiB7XG4gICAgICAgIF9faHRtbDogaXRcbiAgICAgIH1cbiAgICB9O1xuICB9O1xuICBvdXQkLlBhaSA9IFBhaSA9ICRjbGFzcyh7XG4gICAgZGlzcGxheU5hbWU6ICdQYWknLFxuICAgIHJlbmRlcjogZnVuY3Rpb24oKXtcbiAgICAgIHZhciByZWYkLCBwYWksIHgsIHksIHJvdCwgY2xhc3NOYW1lLCB0cmFuc2Zvcm07XG4gICAgICByZWYkID0gdGhpcy5wcm9wcywgcGFpID0gcmVmJC5wYWksIHggPSByZWYkLngsIHkgPSByZWYkLnksIHJvdCA9IHJlZiQucm90LCBjbGFzc05hbWUgPSByZWYkLmNsYXNzTmFtZTtcbiAgICAgIGNsYXNzTmFtZSA9PSBudWxsICYmIChjbGFzc05hbWUgPSAnJyk7XG4gICAgICBjbGFzc05hbWUgKz0gJyBwYWknO1xuICAgICAgaWYgKCEvXlxcZFttcHN6XSQvLnRlc3QocGFpKSkge1xuICAgICAgICByZXR1cm4gbnVsbDtcbiAgICAgIH1cbiAgICAgIHN3aXRjaCAocm90KSB7XG4gICAgICBjYXNlIC0xOlxuICAgICAgICB0cmFuc2Zvcm0gPSBcInJvdGF0ZSgtOTApXCI7XG4gICAgICAgIGJyZWFrO1xuICAgICAgY2FzZSAwOlxuICAgICAgICB0cmFuc2Zvcm0gPSBcInRyYW5zbGF0ZSgwLCAtXCIgKyBQQUlfSCArIFwiKVwiO1xuICAgICAgICBicmVhaztcbiAgICAgIGNhc2UgKzE6XG4gICAgICAgIHRyYW5zZm9ybSA9IFwidHJhbnNsYXRlKFwiICsgUEFJX0ggKyBcIiwgLTEpIHJvdGF0ZSgrOTApXCI7XG4gICAgICB9XG4gICAgICByZXR1cm4gJFsnZyddKGltcG9ydEFsbCQoe1xuICAgICAgICB0cmFuc2Zvcm06IFwidHJhbnNsYXRlKFwiICsgeCArIFwiIFwiICsgeSArIFwiKVwiLFxuICAgICAgICBjbGFzc05hbWU6IGNsYXNzTmFtZVxuICAgICAgfSwgJEhUTUwoXCI8aW1hZ2UgeGxpbms6aHJlZj1cXFwiXCIgKyBQQUlfUEFUSCArIFwiL1wiICsgcGFpICsgXCIuc3ZnXFxcIlxcbiAgd2lkdGg9XFxcIjFcXFwiIGhlaWdodD1cXFwiXCIgKyBQQUlfSCArIFwiXFxcIiBwcmVzZXJ2ZUFzcGVjdFJhdGlvPVxcXCJ4TWlkWU1pZCBzbGljZVxcXCJcXG4gIHRyYW5zZm9ybT1cXFwiXCIgKyB0cmFuc2Zvcm0gKyBcIlxcXCIvPlwiKSkpO1xuICAgIH1cbiAgfSk7XG4gIG91dCQuUGFpUm93ID0gUGFpUm93ID0gJGNsYXNzKHtcbiAgICBkaXNwbGF5TmFtZTogJ1BhaVJvdycsXG4gICAgcmVuZGVyOiBmdW5jdGlvbigpe1xuICAgICAgdmFyIHhOZXh0LCByZWYkLCByaWdodCwgeCwgeTtcbiAgICAgIHhOZXh0ID0gMDtcbiAgICAgIHJlZiQgPSB0aGlzLnByb3BzLCByaWdodCA9IHJlZiQucmlnaHQsIHggPSByZWYkLngsIHkgPSByZWYkLnk7XG4gICAgICByZXR1cm4gJFsnZyddKHtcbiAgICAgICAgdHJhbnNmb3JtOiBcInRyYW5zbGF0ZShcIiArIHggKyBcIiBcIiArIHkgKyBcIilcIlxuICAgICAgfSwgdGhpcy5wcm9wcy5saXN0Lm1hcChmdW5jdGlvbihhcmckLCBpKXtcbiAgICAgICAgdmFyIHBhaSwgcG9zLCBzcGFjZSwgY2xhc3NOYW1lLCB4LCB5LCByb3Q7XG4gICAgICAgIHBhaSA9IGFyZyQucGFpLCBwb3MgPSBhcmckLnBvcywgc3BhY2UgPSBhcmckLnNwYWNlLCBjbGFzc05hbWUgPSBhcmckLmNsYXNzTmFtZTtcbiAgICAgICAgc3dpdGNoIChwb3MpIHtcbiAgICAgICAgY2FzZSAnbCc6XG4gICAgICAgIGNhc2UgJ3InOlxuICAgICAgICAgIHggPSByaWdodCA/IC14TmV4dCAtIFBBSV9IIDogeE5leHQ7XG4gICAgICAgICAgeSA9IDA7XG4gICAgICAgICAgcm90ID0gcG9zID09PSAnbCdcbiAgICAgICAgICAgID8gLTFcbiAgICAgICAgICAgIDogKzE7XG4gICAgICAgICAgeE5leHQgKz0gUEFJX0g7XG4gICAgICAgICAgYnJlYWs7XG4gICAgICAgIGNhc2UgJ0wnOlxuICAgICAgICBjYXNlICdSJzpcbiAgICAgICAgICB4ID0gcmlnaHRcbiAgICAgICAgICAgID8gLXhOZXh0XG4gICAgICAgICAgICA6IHhOZXh0IC0gUEFJX0g7XG4gICAgICAgICAgeSA9IC0xO1xuICAgICAgICAgIHJvdCA9IHBvcyA9PT0gJ0wnXG4gICAgICAgICAgICA/IC0xXG4gICAgICAgICAgICA6ICsxO1xuICAgICAgICAgIGJyZWFrO1xuICAgICAgICBkZWZhdWx0OlxuICAgICAgICAgIHggPSByaWdodCA/IC14TmV4dCAtIDEgOiB4TmV4dDtcbiAgICAgICAgICB5ID0gMDtcbiAgICAgICAgICByb3QgPSAwO1xuICAgICAgICAgIHhOZXh0Kys7XG4gICAgICAgIH1cbiAgICAgICAgaWYgKHNwYWNlKSB7XG4gICAgICAgICAgeE5leHQgKz0gc3BhY2U7XG4gICAgICAgIH1cbiAgICAgICAgcmV0dXJuICRuZXcoUGFpLCB7XG4gICAgICAgICAgcGFpOiBwYWksXG4gICAgICAgICAgeDogeCxcbiAgICAgICAgICB5OiB5LFxuICAgICAgICAgIHJvdDogcm90LFxuICAgICAgICAgIGNsYXNzTmFtZTogY2xhc3NOYW1lICE9IG51bGwgPyBjbGFzc05hbWUgOiAnJyxcbiAgICAgICAgICBrZXk6IGlcbiAgICAgICAgfSk7XG4gICAgICB9KSk7XG4gICAgfVxuICB9KTtcbiAgb3V0JC5TdXRlaGFpID0gU3V0ZWhhaSA9ICRjbGFzcyh7XG4gICAgZGlzcGxheU5hbWU6ICdTdXRlaGFpJyxcbiAgICByZW5kZXI6IGZ1bmN0aW9uKCl7XG4gICAgICB2YXIgcm93cywgcm93LCByZWYkLCB4LCB5LCBtYXhDb2wsIG1heFJvdywgc3V0ZWhhaSwgc2hvd0Z1dXJvLCBpJCwgbGVuJCwgaSwgcGFpLCBmdXVyb1BsYXllciwgdHN1bW9raXJpLCByaWljaGksIGNsYXNzTmFtZSwgcG9zO1xuICAgICAgcm93cyA9IFtdO1xuICAgICAgcm93ID0gW107XG4gICAgICByZWYkID0gdGhpcy5wcm9wcywgeCA9IHJlZiQueCwgeSA9IHJlZiQueSwgbWF4Q29sID0gcmVmJC5tYXhDb2wsIG1heFJvdyA9IHJlZiQubWF4Um93LCBzdXRlaGFpID0gcmVmJC5zdXRlaGFpLCBzaG93RnV1cm8gPSByZWYkLnNob3dGdXVybztcbiAgICAgIGZvciAoaSQgPSAwLCBsZW4kID0gc3V0ZWhhaS5sZW5ndGg7IGkkIDwgbGVuJDsgKytpJCkge1xuICAgICAgICBpID0gaSQ7XG4gICAgICAgIHJlZiQgPSBzdXRlaGFpW2kkXSwgcGFpID0gcmVmJC5wYWksIGZ1dXJvUGxheWVyID0gcmVmJC5mdXVyb1BsYXllciwgdHN1bW9raXJpID0gcmVmJC50c3Vtb2tpcmksIHJpaWNoaSA9IHJlZiQucmlpY2hpO1xuICAgICAgICBjbGFzc05hbWUgPSAnJztcbiAgICAgICAgaWYgKGZ1dXJvUGxheWVyICE9IG51bGwgJiYgIXNob3dGdXVybykge1xuICAgICAgICAgIGNvbnRpbnVlO1xuICAgICAgICB9XG4gICAgICAgIGlmICh0c3Vtb2tpcmkpIHtcbiAgICAgICAgICBjbGFzc05hbWUgKz0gJyBwYWktdHN1bW9raXJpJztcbiAgICAgICAgfVxuICAgICAgICBpZiAocmlpY2hpKSB7XG4gICAgICAgICAgY2xhc3NOYW1lICs9ICcgcGFpLXJpaWNoaSc7XG4gICAgICAgICAgcG9zID0gJ2wnO1xuICAgICAgICB9IGVsc2Uge1xuICAgICAgICAgIHBvcyA9ICd1JztcbiAgICAgICAgfVxuICAgICAgICBpZiAocm93LnB1c2goe1xuICAgICAgICAgIHBhaTogcGFpLFxuICAgICAgICAgIHBvczogcG9zLFxuICAgICAgICAgIGNsYXNzTmFtZTogY2xhc3NOYW1lXG4gICAgICAgIH0pID09PSBtYXhDb2wgJiYgcm93cy5sZW5ndGggPD0gbWF4Um93IC0gMikge1xuICAgICAgICAgIHJvd3MucHVzaChyb3cpO1xuICAgICAgICAgIHJvdyA9IFtdO1xuICAgICAgICB9XG4gICAgICB9XG4gICAgICBpZiAocm93Lmxlbmd0aCkge1xuICAgICAgICByb3dzLnB1c2gocm93KTtcbiAgICAgIH1cbiAgICAgIHJldHVybiAkWydnJ10oe30sIHJvd3MubWFwKGZ1bmN0aW9uKHJvdywgaSl7XG4gICAgICAgIHJldHVybiAkbmV3KFBhaVJvdywge1xuICAgICAgICAgIGxpc3Q6IHJvdyxcbiAgICAgICAgICB4OiB4LFxuICAgICAgICAgIHk6IHkgKyAoaSArIDEpICogUEFJX0gsXG4gICAgICAgICAgcmlnaHQ6IGZhbHNlLFxuICAgICAgICAgIGtleTogaVxuICAgICAgICB9KTtcbiAgICAgIH0pKTtcbiAgICB9XG4gIH0pO1xuICBvdXQkLnJvd0Zyb21GdXVybyA9IHJvd0Zyb21GdXVybztcbiAgZnVuY3Rpb24gcm93RnJvbUZ1dXJvKGZ1dXJvLCBwbGF5ZXIpe1xuICAgIHZhciByZXQsIGkkLCBsZW4kLCBmLCBvd24sIG90aGVyLCBkUDtcbiAgICByZXQgPSBbXTtcbiAgICBmb3IgKGkkID0gMCwgbGVuJCA9IGZ1dXJvLmxlbmd0aDsgaSQgPCBsZW4kOyArK2kkKSB7XG4gICAgICBmID0gZnV1cm9baSRdO1xuICAgICAgb3duID0gZi5vd25QYWkuc29ydCgpO1xuICAgICAgb3RoZXIgPSBmLm90aGVyUGFpO1xuICAgICAgZFAgPSAoZi5vdGhlclBsYXllciAtIHBsYXllciArIDQpICUgNDtcbiAgICAgIHN3aXRjaCAoZi50eXBlLnRvU3RyaW5nKCkudG9Mb3dlckNhc2UoKSkge1xuICAgICAgY2FzZSAnc2h1bnRzdSc6XG4gICAgICBjYXNlICdtaW5rbyc6XG4gICAgICAgIGlmIChkUCA9PT0gMSkge1xuICAgICAgICAgIHJldC5wdXNoKHtcbiAgICAgICAgICAgIHBhaTogb3RoZXIsXG4gICAgICAgICAgICBwb3M6ICdyJ1xuICAgICAgICAgIH0pO1xuICAgICAgICB9XG4gICAgICAgIHJldC5wdXNoKHtcbiAgICAgICAgICBwYWk6IG93blsxXSxcbiAgICAgICAgICBwb3M6ICd1J1xuICAgICAgICB9KTtcbiAgICAgICAgaWYgKGRQID09PSAyKSB7XG4gICAgICAgICAgcmV0LnB1c2goe1xuICAgICAgICAgICAgcGFpOiBvdGhlcixcbiAgICAgICAgICAgIHBvczogJ2wnXG4gICAgICAgICAgfSk7XG4gICAgICAgIH1cbiAgICAgICAgcmV0LnB1c2goe1xuICAgICAgICAgIHBhaTogb3duWzBdLFxuICAgICAgICAgIHBvczogJ3UnXG4gICAgICAgIH0pO1xuICAgICAgICBpZiAoZFAgPT09IDMpIHtcbiAgICAgICAgICByZXQucHVzaCh7XG4gICAgICAgICAgICBwYWk6IG90aGVyLFxuICAgICAgICAgICAgcG9zOiAnbCdcbiAgICAgICAgICB9KTtcbiAgICAgICAgfVxuICAgICAgICBicmVhaztcbiAgICAgIGNhc2UgJ2RhaW1pbmthbic6XG4gICAgICAgIGlmIChkUCA9PT0gMSkge1xuICAgICAgICAgIHJldC5wdXNoKHtcbiAgICAgICAgICAgIHBhaTogb3RoZXIsXG4gICAgICAgICAgICBwb3M6ICdyJ1xuICAgICAgICAgIH0pO1xuICAgICAgICB9XG4gICAgICAgIHJldC5wdXNoKHtcbiAgICAgICAgICBwYWk6IG93blsyXSxcbiAgICAgICAgICBwb3M6ICd1J1xuICAgICAgICB9KTtcbiAgICAgICAgcmV0LnB1c2goe1xuICAgICAgICAgIHBhaTogb3duWzFdLFxuICAgICAgICAgIHBvczogJ3UnXG4gICAgICAgIH0pO1xuICAgICAgICBpZiAoZFAgPT09IDIpIHtcbiAgICAgICAgICByZXQucHVzaCh7XG4gICAgICAgICAgICBwYWk6IG90aGVyLFxuICAgICAgICAgICAgcG9zOiAnbCdcbiAgICAgICAgICB9KTtcbiAgICAgICAgfVxuICAgICAgICByZXQucHVzaCh7XG4gICAgICAgICAgcGFpOiBvd25bMF0sXG4gICAgICAgICAgcG9zOiAndSdcbiAgICAgICAgfSk7XG4gICAgICAgIGlmIChkUCA9PT0gMykge1xuICAgICAgICAgIHJldC5wdXNoKHtcbiAgICAgICAgICAgIHBhaTogb3RoZXIsXG4gICAgICAgICAgICBwb3M6ICdsJ1xuICAgICAgICAgIH0pO1xuICAgICAgICB9XG4gICAgICAgIGJyZWFrO1xuICAgICAgY2FzZSAna2FrYW4nOlxuICAgICAgICBpZiAoZFAgPT09IDEpIHtcbiAgICAgICAgICByZXQucHVzaCh7XG4gICAgICAgICAgICBwYWk6IG90aGVyLFxuICAgICAgICAgICAgcG9zOiAncidcbiAgICAgICAgICB9KTtcbiAgICAgICAgICByZXQucHVzaCh7XG4gICAgICAgICAgICBwYWk6IGYua2FrYW5QYWksXG4gICAgICAgICAgICBwb3M6ICdSJ1xuICAgICAgICAgIH0pO1xuICAgICAgICB9XG4gICAgICAgIHJldC5wdXNoKHtcbiAgICAgICAgICBwYWk6IG93blsxXSxcbiAgICAgICAgICBwb3M6ICd1J1xuICAgICAgICB9KTtcbiAgICAgICAgaWYgKGRQID09PSAyKSB7XG4gICAgICAgICAgcmV0LnB1c2goe1xuICAgICAgICAgICAgcGFpOiBvdGhlcixcbiAgICAgICAgICAgIHBvczogJ2wnXG4gICAgICAgICAgfSk7XG4gICAgICAgICAgcmV0LnB1c2goe1xuICAgICAgICAgICAgcGFpOiBmLmtha2FuUGFpLFxuICAgICAgICAgICAgcG9zOiAnTCdcbiAgICAgICAgICB9KTtcbiAgICAgICAgfVxuICAgICAgICByZXQucHVzaCh7XG4gICAgICAgICAgcGFpOiBvd25bMF0sXG4gICAgICAgICAgcG9zOiAndSdcbiAgICAgICAgfSk7XG4gICAgICAgIGlmIChkUCA9PT0gMykge1xuICAgICAgICAgIHJldC5wdXNoKHtcbiAgICAgICAgICAgIHBhaTogb3RoZXIsXG4gICAgICAgICAgICBwb3M6ICdsJ1xuICAgICAgICAgIH0pO1xuICAgICAgICAgIHJldC5wdXNoKHtcbiAgICAgICAgICAgIHBhaTogZi5rYWthblBhaSxcbiAgICAgICAgICAgIHBvczogJ0wnXG4gICAgICAgICAgfSk7XG4gICAgICAgIH1cbiAgICAgICAgYnJlYWs7XG4gICAgICBjYXNlICdhbmthbic6XG4gICAgICAgIHJldC5wdXNoKHtcbiAgICAgICAgICBwYWk6ICc4eicsXG4gICAgICAgICAgcG9zOiAndSdcbiAgICAgICAgfSk7XG4gICAgICAgIHJldC5wdXNoKHtcbiAgICAgICAgICBwYWk6IG93blsxXSxcbiAgICAgICAgICBwb3M6ICd1J1xuICAgICAgICB9KTtcbiAgICAgICAgcmV0LnB1c2goe1xuICAgICAgICAgIHBhaTogb3duWzBdLFxuICAgICAgICAgIHBvczogJ3UnXG4gICAgICAgIH0pO1xuICAgICAgICByZXQucHVzaCh7XG4gICAgICAgICAgcGFpOiAnOHonLFxuICAgICAgICAgIHBvczogJ3UnXG4gICAgICAgIH0pO1xuICAgICAgICBicmVhaztcbiAgICAgIGRlZmF1bHQ6XG4gICAgICAgIHRocm93IEVycm9yKFwid3RmIHR5cGUgXCIgKyBmLnR5cGUpO1xuICAgICAgfVxuICAgIH1cbiAgICByZXR1cm4gcmV0O1xuICB9XG4gIG91dCQucm93RnJvbUp1bnRlaGFpID0gcm93RnJvbUp1bnRlaGFpO1xuICBmdW5jdGlvbiByb3dGcm9tSnVudGVoYWkoanVudGVoYWksIHRzdW1vKXtcbiAgICB2YXIgcmV0O1xuICAgIHJldCA9IGp1bnRlaGFpLm1hcChmdW5jdGlvbihpdCl7XG4gICAgICByZXR1cm4ge1xuICAgICAgICBwYWk6IGl0LFxuICAgICAgICBwb3M6ICd1JyxcbiAgICAgICAgc3BhY2U6IDBcbiAgICAgIH07XG4gICAgfSk7XG4gICAgaWYgKHRzdW1vKSB7XG4gICAgICByZXRbcmV0Lmxlbmd0aCAtIDFdLnNwYWNlID0gMSAvIDY7XG4gICAgICByZXQucHVzaCh7XG4gICAgICAgIHBhaTogdHN1bW8sXG4gICAgICAgIHBvczogJ3UnLFxuICAgICAgICBzcGFjZTogMFxuICAgICAgfSk7XG4gICAgfVxuICAgIHJldHVybiByZXQ7XG4gIH1cbiAgb3V0JC5yb3dCYWNrID0gcm93QmFjaztcbiAgZnVuY3Rpb24gcm93QmFjayhuLCB0c3Vtbyl7XG4gICAgdmFyIHJldCwgcmVzJCwgaSQsIGk7XG4gICAgcmVzJCA9IFtdO1xuICAgIGZvciAoaSQgPSAwOyBpJCA8IG47ICsraSQpIHtcbiAgICAgIGkgPSBpJDtcbiAgICAgIHJlcyQucHVzaCh7XG4gICAgICAgIHBhaTogJzh6JyxcbiAgICAgICAgcG9zOiAndScsXG4gICAgICAgIHNwYWNlOiAwXG4gICAgICB9KTtcbiAgICB9XG4gICAgcmV0ID0gcmVzJDtcbiAgICBpZiAodHN1bW8pIHtcbiAgICAgIHJldFtyZXQubGVuZ3RoIC0gMV0uc3BhY2UgPSAxIC8gNjtcbiAgICAgIHJldC5wdXNoKHtcbiAgICAgICAgcGFpOiAnOHonLFxuICAgICAgICBwb3M6ICd1JyxcbiAgICAgICAgc3BhY2U6IDBcbiAgICAgIH0pO1xuICAgIH1cbiAgICByZXR1cm4gcmV0O1xuICB9XG4gIGZ1bmN0aW9uIGltcG9ydEFsbCQob2JqLCBzcmMpe1xuICAgIGZvciAodmFyIGtleSBpbiBzcmMpIG9ialtrZXldID0gc3JjW2tleV07XG4gICAgcmV0dXJuIG9iajtcbiAgfVxufSkuY2FsbCh0aGlzKTtcbiIsIi8vIEdlbmVyYXRlZCBieSBMaXZlU2NyaXB0IDEuNC4wXG4oZnVuY3Rpb24oKXtcbiAgdmFyIGVudGl0eU1hcCwgb3V0JCA9IHR5cGVvZiBleHBvcnRzICE9ICd1bmRlZmluZWQnICYmIGV4cG9ydHMgfHwgdGhpcztcbiAgb3V0JC51dGY4X3RvX2I2NCA9IHV0ZjhfdG9fYjY0O1xuICBmdW5jdGlvbiB1dGY4X3RvX2I2NChpdCl7XG4gICAgcmV0dXJuIHdpbmRvdy5idG9hKHVuZXNjYXBlKGVuY29kZVVSSUNvbXBvbmVudChpdCkpKTtcbiAgfVxuICBvdXQkLmI2NF90b191dGY4ID0gYjY0X3RvX3V0Zjg7XG4gIGZ1bmN0aW9uIGI2NF90b191dGY4KGl0KXtcbiAgICByZXR1cm4gZGVjb2RlVVJJQ29tcG9uZW50KGVzY2FwZSh3aW5kb3cuYXRvYihpdCkpKTtcbiAgfVxuICBvdXQkLmdldERhdGFVUkkgPSBnZXREYXRhVVJJO1xuICBmdW5jdGlvbiBnZXREYXRhVVJJKGl0KXtcbiAgICByZXR1cm4gJ2RhdGE6dGV4dC9odG1sO2Jhc2U2NCwnICsgdXRmOF90b19iNjQoaXQpO1xuICB9XG4gIGVudGl0eU1hcCA9IHtcbiAgICBcIiZcIjogXCImYW1wO1wiLFxuICAgIFwiPFwiOiBcIiZsdDtcIixcbiAgICBcIj5cIjogXCImZ3Q7XCIsXG4gICAgJ1wiJzogJyZxdW90OycsXG4gICAgXCInXCI6ICcmIzM5OycsXG4gICAgXCIvXCI6ICcmI3gyRjsnXG4gIH07XG4gIG91dCQuZXNjYXBlSFRNTCA9IGVzY2FwZUhUTUw7XG4gIGZ1bmN0aW9uIGVzY2FwZUhUTUwoaXQpe1xuICAgIHJldHVybiBTdHJpbmcoaXQpLnJlcGxhY2UoL1smPD5cIidcXC9dL2csIGZ1bmN0aW9uKGl0KXtcbiAgICAgIHJldHVybiBlbnRpdHlNYXBbaXRdO1xuICAgIH0pO1xuICB9XG59KS5jYWxsKHRoaXMpO1xuIiwiLy8gR2VuZXJhdGVkIGJ5IExpdmVTY3JpcHQgMS40LjBcbihmdW5jdGlvbigpe1xuICB2YXIgZXNjYXBlSFRNTCwgcmVmJCwgU0VSVkVSLCBQUkVGSVgsIHVpLCBxUywgcVNBLCBzdmcsIGNvbiwgZGVidWdTdHIsIGRlYnVnLCBnYW1lSWQsIEcsIHBsYXllck5hbWUsIHBsYXllclRva2VuLCBwbGF5ZXJTZWF0LCBwbGF5ZXJOYW1lcywgc3Vic2NyaXB0aW9uLCBjb25uLCBTO1xuICBlc2NhcGVIVE1MID0gcmVxdWlyZSgnLi91dGlsJykuZXNjYXBlSFRNTDtcbiAgcmVmJCA9IHJlcXVpcmUoJy4vY29uZicpLCBTRVJWRVIgPSByZWYkLlNFUlZFUiwgUFJFRklYID0gcmVmJC5QUkVGSVg7XG4gIHVpID0gcmVxdWlyZSgnLi91aScpO1xuICBxUyA9IGZ1bmN0aW9uKGl0KXtcbiAgICByZXR1cm4gZG9jdW1lbnQucXVlcnlTZWxlY3RvcihpdCk7XG4gIH07XG4gIHFTQSA9IGZ1bmN0aW9uKGl0KXtcbiAgICByZXR1cm4gZG9jdW1lbnQucXVlcnlTZWxlY3RvckFsbChpdCk7XG4gIH07XG4gIHN2ZyA9IHFTKCcjbWFpbicpO1xuICBjb24gPSBxUygnI2NvbicpO1xuICBkZWJ1Z1N0ciA9IGNvbi5pbm5lckhUTUw7XG4gIGRlYnVnID0gZnVuY3Rpb24oaXQpe1xuICAgIGNvbi5pbm5lckhUTUwgPSBkZWJ1Z1N0ciArPSBlc2NhcGVIVE1MKGl0KSArICdcXG4nO1xuICB9O1xuICBnYW1lSWQgPSBudWxsO1xuICBHID0gbnVsbDtcbiAgcGxheWVyTmFtZSA9IG51bGw7XG4gIHBsYXllclRva2VuID0gbnVsbDtcbiAgcGxheWVyU2VhdCA9IG51bGw7XG4gIHBsYXllck5hbWVzID0gbnVsbDtcbiAgKGZ1bmN0aW9uKCl7XG4gICAgdmFyIHMsIGosIGdhbWVJZCwgcGxheWVyTmFtZXMsIHBsYXllclNlYXQsIHBsYXllclRva2VuLCBlO1xuICAgIHRyeSB7XG4gICAgICBzID0gZG9jdW1lbnQubG9jYXRpb24uaGFzaC5zdWJzdHIoMSk7XG4gICAgICBqID0gSlNPTi5wYXJzZShkZWNvZGVVUklDb21wb25lbnQocykpO1xuICAgICAgZ2FtZUlkID0gai5nYW1lSWQsIHBsYXllck5hbWVzID0gai5wbGF5ZXJOYW1lcywgcGxheWVyU2VhdCA9IGoucGxheWVyU2VhdCwgcGxheWVyVG9rZW4gPSBqLnBsYXllclRva2VuO1xuICAgIH0gY2F0Y2ggKGUkKSB7XG4gICAgICBlID0gZSQ7XG4gICAgICBkZWJ1ZyhcImludmFsaWQgZ2FtZSBVUkxcIik7XG4gICAgICB0aHJvdyBlO1xuICAgIH1cbiAgfSkoKTtcbiAgc3Vic2NyaXB0aW9uID0gbnVsbDtcbiAgZnVuY3Rpb24gc3Vic2NyaWJlKCl7XG4gICAgcmV0dXJuIHN1YnNjcmlwdGlvbiA9IFMuc3Vic2NyaWJlKEcsIG9uR2FtZUV2ZW50KTtcbiAgfVxuICBmdW5jdGlvbiB1blN1YnNjcmliZSgpe1xuICAgIGlmIChzdWJzY3JpcHRpb24pIHtcbiAgICAgIHJldHVybiBTLnVuc3Vic2NyaWJlKHN1YnNjcmlwdGlvbik7XG4gICAgfVxuICB9XG4gIGNvbm4gPSBuZXcgYXV0b2JhaG4uQ29ubmVjdGlvbihTRVJWRVIpO1xuICBTID0gbnVsbDtcbiAgY29ubi5vbm9wZW4gPSBvbk9wZW47XG4gIGNvbm4ub25jbG9zZSA9IG9uQ2xvc2U7XG4gIHByb2Nlc3MubmV4dFRpY2soZnVuY3Rpb24oKXtcbiAgICBkZWJ1ZyhcImNvbm5lY3RpbmcgdG8gXCIgKyBTRVJWRVIudXJsICsgXCIgLi4uXCIpO1xuICAgIHJldHVybiBjb25uLm9wZW4oKTtcbiAgfSk7XG4gIGZ1bmN0aW9uIG9uT3Blbigpe1xuICAgIGRlYnVnKFwiY29ubmVjdGVkXCIpO1xuICAgIHJldHVybiBTID0gY29ubi5zZXNzaW9uO1xuICB9XG4gIGZ1bmN0aW9uIG9uQ2xvc2UocmVhc29uLCBkZXRhaWxzKXtcbiAgICBkZWJ1ZyhcImxvc3QgY29ubmVjdGlvbi4gcmVhc29uOiBcIiArIHJlYXNvbik7XG4gICAgY29uc29sZS5lcnJvcihkZXRhaWxzKTtcbiAgICByZXR1cm4gUyA9IG51bGw7XG4gIH1cbiAgZnVuY3Rpb24gb25HYW1lRXZlbnQoYXJncywga3dhcmdzKXtcbiAgICB2YXIgdHlwZSwgZGV0YWlscztcbiAgICB0eXBlID0gYXJnc1swXSwgZGV0YWlscyA9IGFyZ3NbMV07XG4gICAgdGhyb3cgRXJyb3IoJ3VuaW1wbGVtZW50ZWQnKTtcbiAgfVxufSkuY2FsbCh0aGlzKTtcbiJdfQ==
