(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
// shim for using process in browser

var process = module.exports = {};
var queue = [];
var draining = false;
var currentQueue;
var queueIndex = -1;

function cleanUpNextTick() {
    draining = false;
    if (currentQueue.length) {
        queue = currentQueue.concat(queue);
    } else {
        queueIndex = -1;
    }
    if (queue.length) {
        drainQueue();
    }
}

function drainQueue() {
    if (draining) {
        return;
    }
    var timeout = setTimeout(cleanUpNextTick);
    draining = true;

    var len = queue.length;
    while(len) {
        currentQueue = queue;
        queue = [];
        while (++queueIndex < len) {
            currentQueue[queueIndex].run();
        }
        queueIndex = -1;
        len = queue.length;
    }
    currentQueue = null;
    draining = false;
    clearTimeout(timeout);
}

process.nextTick = function (fun) {
    var args = new Array(arguments.length - 1);
    if (arguments.length > 1) {
        for (var i = 1; i < arguments.length; i++) {
            args[i - 1] = arguments[i];
        }
    }
    queue.push(new Item(fun, args));
    if (!draining) {
        setTimeout(drainQueue, 0);
    }
};

// v8 likes predictible objects
function Item(fun, array) {
    this.fun = fun;
    this.array = array;
}
Item.prototype.run = function () {
    this.fun.apply(null, this.array);
};
process.title = 'browser';
process.browser = true;
process.env = {};
process.argv = [];
process.version = ''; // empty string to avoid regexp issues
process.versions = {};

function noop() {}

process.on = noop;
process.addListener = noop;
process.once = noop;
process.off = noop;
process.removeListener = noop;
process.removeAllListeners = noop;
process.emit = noop;

process.binding = function (name) {
    throw new Error('process.binding is not supported');
};

// TODO(shtylman)
process.cwd = function () { return '/' };
process.chdir = function (dir) {
    throw new Error('process.chdir is not supported');
};
process.umask = function() { return 0; };

},{}],2:[function(require,module,exports){
// Generated by LiveScript 1.4.0
(function(){
  module.exports = {
    SERVER: {
      url: 'ws://localhost:8000/ws',
      realm: 'riichi'
    },
    PREFIX: 'io.github.summivox.riichi',
    PAI_H: 1.3,
    PAI_PATH: "img/pai"
  };
}).call(this);

},{}],3:[function(require,module,exports){
// Generated by LiveScript 1.4.0
(function(){
  var entityMap, out$ = typeof exports != 'undefined' && exports || this;
  out$.utf8_to_b64 = utf8_to_b64;
  function utf8_to_b64(it){
    return window.btoa(unescape(encodeURIComponent(it)));
  }
  out$.b64_to_utf8 = b64_to_utf8;
  function b64_to_utf8(it){
    return decodeURIComponent(escape(window.atob(it)));
  }
  out$.getDataURI = getDataURI;
  function getDataURI(it){
    return 'data:text/html;base64,' + utf8_to_b64(it);
  }
  entityMap = {
    "&": "&amp;",
    "<": "&lt;",
    ">": "&gt;",
    '"': '&quot;',
    "'": '&#39;',
    "/": '&#x2F;'
  };
  out$.escapeHTML = escapeHTML;
  function escapeHTML(it){
    return String(it).replace(/[&<>"'\/]/g, function(it){
      return entityMap[it];
    });
  }
}).call(this);

},{}],4:[function(require,module,exports){
(function (process){
// Generated by LiveScript 1.4.0
(function(){
  var ref$, utf8_to_b64, escapeHTML, SERVER, PREFIX, qS, qSA, inputGameId, btnNew, inputName, btnJoin, btnLeave, con, debugStr, debug, joined, updateJoined, gameId, G, playerName, playerToken, playerSeat, playerNames, conn, S, subscription;
  ref$ = require('./util'), utf8_to_b64 = ref$.utf8_to_b64, escapeHTML = ref$.escapeHTML;
  ref$ = require('./conf'), SERVER = ref$.SERVER, PREFIX = ref$.PREFIX;
  qS = function(it){
    return document.querySelector(it);
  };
  qSA = function(it){
    return document.querySelectorAll(it);
  };
  inputGameId = qS('#inputGameId');
  btnNew = qS('#btnNew');
  inputName = qS('#inputName');
  btnJoin = qS('#btnJoin');
  btnLeave = qS('#btnLeave');
  con = qS('#con');
  debugStr = con.innerHTML;
  debug = function(it){
    con.innerHTML = debugStr += escapeHTML(it) + '\n';
  };
  joined = false;
  updateJoined = function(it){
    joined = it;
    btnJoin.disabled = joined;
    return btnLeave.disabled = !joined;
  };
  gameId = null;
  G = null;
  playerName = null;
  playerToken = null;
  playerSeat = null;
  playerNames = null;
  conn = new autobahn.Connection(SERVER);
  S = null;
  conn.onopen = onOpen;
  conn.onclose = onClose;
  process.nextTick(function(){
    debug("connecting to " + SERVER.url + " ...");
    return conn.open();
  });
  function onOpen(){
    debug("connected");
    return S = conn.session;
  }
  function onClose(reason, details){
    debug("lost connection. reason: " + reason);
    console.error(details);
    S = null;
    return updateJoined(false);
  }
  btnNew.addEventListener('click', function(){
    if (!(S != null && S.isOpen)) {
      return debug("error: not connected yet");
    }
    debug("try create new game...");
    return S.call(PREFIX + ".game.new").then(function(gameId){
      debug("  new game " + gameId + " created");
      return inputGameId.value = gameId;
    })['catch'](function(err){
      debug("  error: " + err);
      return console.error(err);
    });
  });
  btnJoin.addEventListener('click', function(){
    if (!(S != null && S.isOpen)) {
      return debug("error: not connected yet");
    }
    if (joined) {
      return debug("error: already joined");
    }
    if ((gameId = inputGameId.value.trim()).length === 0) {
      return debug("empty game id");
    }
    playerName = inputName.value.trim();
    G = PREFIX + ".game." + gameId;
    return subscribe().then(function(){
      debug("joining...");
      return S.call(G + ".join", [playerName]);
    }).then(function(token){
      debug("  joined. player token: " + token);
      playerToken = token;
      return updateJoined(true);
    })['catch'](function(err){
      debug("  error: " + err);
      console.error(err);
      return unSubscribe();
    });
  });
  btnLeave.addEventListener('click', function(){
    if (!(S != null && S.isOpen)) {
      return debug("error: not connected yet");
    }
    if (!joined) {
      return debug("error: not joined");
    }
    debug("leaving...");
    return S.call(G + ".leave", [playerToken]).then(function(){
      debug("  leaved.");
      playerToken = null;
      updateJoined(false);
      return unSubscribe();
    })['catch'](function(err){
      debug("  error: " + err);
      return console.error(err);
    });
  });
  subscription = null;
  function subscribe(){
    return S.subscribe(G, handler).then(function(it){
      return subscription = it;
    });
  }
  function unSubscribe(){
    if (subscription) {
      return S.unsubscribe(subscription);
    }
  }
  function handler(args){
    var type, details;
    type = args[0], details = args[1];
    switch (type) {
    case 'join':
      return debug("player " + details + " has joined");
    case 'leave':
      return debug("player " + details + " has leaved");
    case 'start':
      playerNames = details;
      playerSeat = playerNames.indexOf(playerName);
      if (playerSeat === -1) {
        debug("game started without you (WTF?)");
        return conn.close();
      } else {
        return startGame();
      }
    }
  }
  function startGame(){
    var args, s;
    conn.close();
    args = {
      gameId: gameId,
      playerNames: playerNames,
      playerSeat: playerSeat,
      playerToken: playerToken
    };
    s = encodeURIComponent(JSON.stringify(args));
    return window.location = 'game.html#' + s;
  }
}).call(this);

}).call(this,require('_process'))

},{"./conf":2,"./util":3,"_process":1}]},{},[4])
//# sourceMappingURL=data:application/json;charset:utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbImM6L1VzZXJzL1lpbiBaaG9uZy9BcHBEYXRhL1JvYW1pbmcvbnBtL25vZGVfbW9kdWxlcy9icm93c2VyaWZ5L25vZGVfbW9kdWxlcy9icm93c2VyLXBhY2svX3ByZWx1ZGUuanMiLCJjOi9Vc2Vycy9ZaW4gWmhvbmcvQXBwRGF0YS9Sb2FtaW5nL25wbS9ub2RlX21vZHVsZXMvYnJvd3NlcmlmeS9ub2RlX21vZHVsZXMvcHJvY2Vzcy9icm93c2VyLmpzIiwiY29uZi5qcyIsInV0aWwuanMiLCJpbmRleC5qcyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFBQTtBQ0FBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBOztBQzFGQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTs7QUNaQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTs7O0FDOUJBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBIiwiZmlsZSI6ImdlbmVyYXRlZC5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzQ29udGVudCI6WyIoZnVuY3Rpb24gZSh0LG4scil7ZnVuY3Rpb24gcyhvLHUpe2lmKCFuW29dKXtpZighdFtvXSl7dmFyIGE9dHlwZW9mIHJlcXVpcmU9PVwiZnVuY3Rpb25cIiYmcmVxdWlyZTtpZighdSYmYSlyZXR1cm4gYShvLCEwKTtpZihpKXJldHVybiBpKG8sITApO3ZhciBmPW5ldyBFcnJvcihcIkNhbm5vdCBmaW5kIG1vZHVsZSAnXCIrbytcIidcIik7dGhyb3cgZi5jb2RlPVwiTU9EVUxFX05PVF9GT1VORFwiLGZ9dmFyIGw9bltvXT17ZXhwb3J0czp7fX07dFtvXVswXS5jYWxsKGwuZXhwb3J0cyxmdW5jdGlvbihlKXt2YXIgbj10W29dWzFdW2VdO3JldHVybiBzKG4/bjplKX0sbCxsLmV4cG9ydHMsZSx0LG4scil9cmV0dXJuIG5bb10uZXhwb3J0c312YXIgaT10eXBlb2YgcmVxdWlyZT09XCJmdW5jdGlvblwiJiZyZXF1aXJlO2Zvcih2YXIgbz0wO288ci5sZW5ndGg7bysrKXMocltvXSk7cmV0dXJuIHN9KSIsIi8vIHNoaW0gZm9yIHVzaW5nIHByb2Nlc3MgaW4gYnJvd3NlclxuXG52YXIgcHJvY2VzcyA9IG1vZHVsZS5leHBvcnRzID0ge307XG52YXIgcXVldWUgPSBbXTtcbnZhciBkcmFpbmluZyA9IGZhbHNlO1xudmFyIGN1cnJlbnRRdWV1ZTtcbnZhciBxdWV1ZUluZGV4ID0gLTE7XG5cbmZ1bmN0aW9uIGNsZWFuVXBOZXh0VGljaygpIHtcbiAgICBkcmFpbmluZyA9IGZhbHNlO1xuICAgIGlmIChjdXJyZW50UXVldWUubGVuZ3RoKSB7XG4gICAgICAgIHF1ZXVlID0gY3VycmVudFF1ZXVlLmNvbmNhdChxdWV1ZSk7XG4gICAgfSBlbHNlIHtcbiAgICAgICAgcXVldWVJbmRleCA9IC0xO1xuICAgIH1cbiAgICBpZiAocXVldWUubGVuZ3RoKSB7XG4gICAgICAgIGRyYWluUXVldWUoKTtcbiAgICB9XG59XG5cbmZ1bmN0aW9uIGRyYWluUXVldWUoKSB7XG4gICAgaWYgKGRyYWluaW5nKSB7XG4gICAgICAgIHJldHVybjtcbiAgICB9XG4gICAgdmFyIHRpbWVvdXQgPSBzZXRUaW1lb3V0KGNsZWFuVXBOZXh0VGljayk7XG4gICAgZHJhaW5pbmcgPSB0cnVlO1xuXG4gICAgdmFyIGxlbiA9IHF1ZXVlLmxlbmd0aDtcbiAgICB3aGlsZShsZW4pIHtcbiAgICAgICAgY3VycmVudFF1ZXVlID0gcXVldWU7XG4gICAgICAgIHF1ZXVlID0gW107XG4gICAgICAgIHdoaWxlICgrK3F1ZXVlSW5kZXggPCBsZW4pIHtcbiAgICAgICAgICAgIGN1cnJlbnRRdWV1ZVtxdWV1ZUluZGV4XS5ydW4oKTtcbiAgICAgICAgfVxuICAgICAgICBxdWV1ZUluZGV4ID0gLTE7XG4gICAgICAgIGxlbiA9IHF1ZXVlLmxlbmd0aDtcbiAgICB9XG4gICAgY3VycmVudFF1ZXVlID0gbnVsbDtcbiAgICBkcmFpbmluZyA9IGZhbHNlO1xuICAgIGNsZWFyVGltZW91dCh0aW1lb3V0KTtcbn1cblxucHJvY2Vzcy5uZXh0VGljayA9IGZ1bmN0aW9uIChmdW4pIHtcbiAgICB2YXIgYXJncyA9IG5ldyBBcnJheShhcmd1bWVudHMubGVuZ3RoIC0gMSk7XG4gICAgaWYgKGFyZ3VtZW50cy5sZW5ndGggPiAxKSB7XG4gICAgICAgIGZvciAodmFyIGkgPSAxOyBpIDwgYXJndW1lbnRzLmxlbmd0aDsgaSsrKSB7XG4gICAgICAgICAgICBhcmdzW2kgLSAxXSA9IGFyZ3VtZW50c1tpXTtcbiAgICAgICAgfVxuICAgIH1cbiAgICBxdWV1ZS5wdXNoKG5ldyBJdGVtKGZ1biwgYXJncykpO1xuICAgIGlmICghZHJhaW5pbmcpIHtcbiAgICAgICAgc2V0VGltZW91dChkcmFpblF1ZXVlLCAwKTtcbiAgICB9XG59O1xuXG4vLyB2OCBsaWtlcyBwcmVkaWN0aWJsZSBvYmplY3RzXG5mdW5jdGlvbiBJdGVtKGZ1biwgYXJyYXkpIHtcbiAgICB0aGlzLmZ1biA9IGZ1bjtcbiAgICB0aGlzLmFycmF5ID0gYXJyYXk7XG59XG5JdGVtLnByb3RvdHlwZS5ydW4gPSBmdW5jdGlvbiAoKSB7XG4gICAgdGhpcy5mdW4uYXBwbHkobnVsbCwgdGhpcy5hcnJheSk7XG59O1xucHJvY2Vzcy50aXRsZSA9ICdicm93c2VyJztcbnByb2Nlc3MuYnJvd3NlciA9IHRydWU7XG5wcm9jZXNzLmVudiA9IHt9O1xucHJvY2Vzcy5hcmd2ID0gW107XG5wcm9jZXNzLnZlcnNpb24gPSAnJzsgLy8gZW1wdHkgc3RyaW5nIHRvIGF2b2lkIHJlZ2V4cCBpc3N1ZXNcbnByb2Nlc3MudmVyc2lvbnMgPSB7fTtcblxuZnVuY3Rpb24gbm9vcCgpIHt9XG5cbnByb2Nlc3Mub24gPSBub29wO1xucHJvY2Vzcy5hZGRMaXN0ZW5lciA9IG5vb3A7XG5wcm9jZXNzLm9uY2UgPSBub29wO1xucHJvY2Vzcy5vZmYgPSBub29wO1xucHJvY2Vzcy5yZW1vdmVMaXN0ZW5lciA9IG5vb3A7XG5wcm9jZXNzLnJlbW92ZUFsbExpc3RlbmVycyA9IG5vb3A7XG5wcm9jZXNzLmVtaXQgPSBub29wO1xuXG5wcm9jZXNzLmJpbmRpbmcgPSBmdW5jdGlvbiAobmFtZSkge1xuICAgIHRocm93IG5ldyBFcnJvcigncHJvY2Vzcy5iaW5kaW5nIGlzIG5vdCBzdXBwb3J0ZWQnKTtcbn07XG5cbi8vIFRPRE8oc2h0eWxtYW4pXG5wcm9jZXNzLmN3ZCA9IGZ1bmN0aW9uICgpIHsgcmV0dXJuICcvJyB9O1xucHJvY2Vzcy5jaGRpciA9IGZ1bmN0aW9uIChkaXIpIHtcbiAgICB0aHJvdyBuZXcgRXJyb3IoJ3Byb2Nlc3MuY2hkaXIgaXMgbm90IHN1cHBvcnRlZCcpO1xufTtcbnByb2Nlc3MudW1hc2sgPSBmdW5jdGlvbigpIHsgcmV0dXJuIDA7IH07XG4iLCIvLyBHZW5lcmF0ZWQgYnkgTGl2ZVNjcmlwdCAxLjQuMFxuKGZ1bmN0aW9uKCl7XG4gIG1vZHVsZS5leHBvcnRzID0ge1xuICAgIFNFUlZFUjoge1xuICAgICAgdXJsOiAnd3M6Ly9sb2NhbGhvc3Q6ODAwMC93cycsXG4gICAgICByZWFsbTogJ3JpaWNoaSdcbiAgICB9LFxuICAgIFBSRUZJWDogJ2lvLmdpdGh1Yi5zdW1taXZveC5yaWljaGknLFxuICAgIFBBSV9IOiAxLjMsXG4gICAgUEFJX1BBVEg6IFwiaW1nL3BhaVwiXG4gIH07XG59KS5jYWxsKHRoaXMpO1xuIiwiLy8gR2VuZXJhdGVkIGJ5IExpdmVTY3JpcHQgMS40LjBcbihmdW5jdGlvbigpe1xuICB2YXIgZW50aXR5TWFwLCBvdXQkID0gdHlwZW9mIGV4cG9ydHMgIT0gJ3VuZGVmaW5lZCcgJiYgZXhwb3J0cyB8fCB0aGlzO1xuICBvdXQkLnV0ZjhfdG9fYjY0ID0gdXRmOF90b19iNjQ7XG4gIGZ1bmN0aW9uIHV0ZjhfdG9fYjY0KGl0KXtcbiAgICByZXR1cm4gd2luZG93LmJ0b2EodW5lc2NhcGUoZW5jb2RlVVJJQ29tcG9uZW50KGl0KSkpO1xuICB9XG4gIG91dCQuYjY0X3RvX3V0ZjggPSBiNjRfdG9fdXRmODtcbiAgZnVuY3Rpb24gYjY0X3RvX3V0ZjgoaXQpe1xuICAgIHJldHVybiBkZWNvZGVVUklDb21wb25lbnQoZXNjYXBlKHdpbmRvdy5hdG9iKGl0KSkpO1xuICB9XG4gIG91dCQuZ2V0RGF0YVVSSSA9IGdldERhdGFVUkk7XG4gIGZ1bmN0aW9uIGdldERhdGFVUkkoaXQpe1xuICAgIHJldHVybiAnZGF0YTp0ZXh0L2h0bWw7YmFzZTY0LCcgKyB1dGY4X3RvX2I2NChpdCk7XG4gIH1cbiAgZW50aXR5TWFwID0ge1xuICAgIFwiJlwiOiBcIiZhbXA7XCIsXG4gICAgXCI8XCI6IFwiJmx0O1wiLFxuICAgIFwiPlwiOiBcIiZndDtcIixcbiAgICAnXCInOiAnJnF1b3Q7JyxcbiAgICBcIidcIjogJyYjMzk7JyxcbiAgICBcIi9cIjogJyYjeDJGOydcbiAgfTtcbiAgb3V0JC5lc2NhcGVIVE1MID0gZXNjYXBlSFRNTDtcbiAgZnVuY3Rpb24gZXNjYXBlSFRNTChpdCl7XG4gICAgcmV0dXJuIFN0cmluZyhpdCkucmVwbGFjZSgvWyY8PlwiJ1xcL10vZywgZnVuY3Rpb24oaXQpe1xuICAgICAgcmV0dXJuIGVudGl0eU1hcFtpdF07XG4gICAgfSk7XG4gIH1cbn0pLmNhbGwodGhpcyk7XG4iLCIvLyBHZW5lcmF0ZWQgYnkgTGl2ZVNjcmlwdCAxLjQuMFxuKGZ1bmN0aW9uKCl7XG4gIHZhciByZWYkLCB1dGY4X3RvX2I2NCwgZXNjYXBlSFRNTCwgU0VSVkVSLCBQUkVGSVgsIHFTLCBxU0EsIGlucHV0R2FtZUlkLCBidG5OZXcsIGlucHV0TmFtZSwgYnRuSm9pbiwgYnRuTGVhdmUsIGNvbiwgZGVidWdTdHIsIGRlYnVnLCBqb2luZWQsIHVwZGF0ZUpvaW5lZCwgZ2FtZUlkLCBHLCBwbGF5ZXJOYW1lLCBwbGF5ZXJUb2tlbiwgcGxheWVyU2VhdCwgcGxheWVyTmFtZXMsIGNvbm4sIFMsIHN1YnNjcmlwdGlvbjtcbiAgcmVmJCA9IHJlcXVpcmUoJy4vdXRpbCcpLCB1dGY4X3RvX2I2NCA9IHJlZiQudXRmOF90b19iNjQsIGVzY2FwZUhUTUwgPSByZWYkLmVzY2FwZUhUTUw7XG4gIHJlZiQgPSByZXF1aXJlKCcuL2NvbmYnKSwgU0VSVkVSID0gcmVmJC5TRVJWRVIsIFBSRUZJWCA9IHJlZiQuUFJFRklYO1xuICBxUyA9IGZ1bmN0aW9uKGl0KXtcbiAgICByZXR1cm4gZG9jdW1lbnQucXVlcnlTZWxlY3RvcihpdCk7XG4gIH07XG4gIHFTQSA9IGZ1bmN0aW9uKGl0KXtcbiAgICByZXR1cm4gZG9jdW1lbnQucXVlcnlTZWxlY3RvckFsbChpdCk7XG4gIH07XG4gIGlucHV0R2FtZUlkID0gcVMoJyNpbnB1dEdhbWVJZCcpO1xuICBidG5OZXcgPSBxUygnI2J0bk5ldycpO1xuICBpbnB1dE5hbWUgPSBxUygnI2lucHV0TmFtZScpO1xuICBidG5Kb2luID0gcVMoJyNidG5Kb2luJyk7XG4gIGJ0bkxlYXZlID0gcVMoJyNidG5MZWF2ZScpO1xuICBjb24gPSBxUygnI2NvbicpO1xuICBkZWJ1Z1N0ciA9IGNvbi5pbm5lckhUTUw7XG4gIGRlYnVnID0gZnVuY3Rpb24oaXQpe1xuICAgIGNvbi5pbm5lckhUTUwgPSBkZWJ1Z1N0ciArPSBlc2NhcGVIVE1MKGl0KSArICdcXG4nO1xuICB9O1xuICBqb2luZWQgPSBmYWxzZTtcbiAgdXBkYXRlSm9pbmVkID0gZnVuY3Rpb24oaXQpe1xuICAgIGpvaW5lZCA9IGl0O1xuICAgIGJ0bkpvaW4uZGlzYWJsZWQgPSBqb2luZWQ7XG4gICAgcmV0dXJuIGJ0bkxlYXZlLmRpc2FibGVkID0gIWpvaW5lZDtcbiAgfTtcbiAgZ2FtZUlkID0gbnVsbDtcbiAgRyA9IG51bGw7XG4gIHBsYXllck5hbWUgPSBudWxsO1xuICBwbGF5ZXJUb2tlbiA9IG51bGw7XG4gIHBsYXllclNlYXQgPSBudWxsO1xuICBwbGF5ZXJOYW1lcyA9IG51bGw7XG4gIGNvbm4gPSBuZXcgYXV0b2JhaG4uQ29ubmVjdGlvbihTRVJWRVIpO1xuICBTID0gbnVsbDtcbiAgY29ubi5vbm9wZW4gPSBvbk9wZW47XG4gIGNvbm4ub25jbG9zZSA9IG9uQ2xvc2U7XG4gIHByb2Nlc3MubmV4dFRpY2soZnVuY3Rpb24oKXtcbiAgICBkZWJ1ZyhcImNvbm5lY3RpbmcgdG8gXCIgKyBTRVJWRVIudXJsICsgXCIgLi4uXCIpO1xuICAgIHJldHVybiBjb25uLm9wZW4oKTtcbiAgfSk7XG4gIGZ1bmN0aW9uIG9uT3Blbigpe1xuICAgIGRlYnVnKFwiY29ubmVjdGVkXCIpO1xuICAgIHJldHVybiBTID0gY29ubi5zZXNzaW9uO1xuICB9XG4gIGZ1bmN0aW9uIG9uQ2xvc2UocmVhc29uLCBkZXRhaWxzKXtcbiAgICBkZWJ1ZyhcImxvc3QgY29ubmVjdGlvbi4gcmVhc29uOiBcIiArIHJlYXNvbik7XG4gICAgY29uc29sZS5lcnJvcihkZXRhaWxzKTtcbiAgICBTID0gbnVsbDtcbiAgICByZXR1cm4gdXBkYXRlSm9pbmVkKGZhbHNlKTtcbiAgfVxuICBidG5OZXcuYWRkRXZlbnRMaXN0ZW5lcignY2xpY2snLCBmdW5jdGlvbigpe1xuICAgIGlmICghKFMgIT0gbnVsbCAmJiBTLmlzT3BlbikpIHtcbiAgICAgIHJldHVybiBkZWJ1ZyhcImVycm9yOiBub3QgY29ubmVjdGVkIHlldFwiKTtcbiAgICB9XG4gICAgZGVidWcoXCJ0cnkgY3JlYXRlIG5ldyBnYW1lLi4uXCIpO1xuICAgIHJldHVybiBTLmNhbGwoUFJFRklYICsgXCIuZ2FtZS5uZXdcIikudGhlbihmdW5jdGlvbihnYW1lSWQpe1xuICAgICAgZGVidWcoXCIgIG5ldyBnYW1lIFwiICsgZ2FtZUlkICsgXCIgY3JlYXRlZFwiKTtcbiAgICAgIHJldHVybiBpbnB1dEdhbWVJZC52YWx1ZSA9IGdhbWVJZDtcbiAgICB9KVsnY2F0Y2gnXShmdW5jdGlvbihlcnIpe1xuICAgICAgZGVidWcoXCIgIGVycm9yOiBcIiArIGVycik7XG4gICAgICByZXR1cm4gY29uc29sZS5lcnJvcihlcnIpO1xuICAgIH0pO1xuICB9KTtcbiAgYnRuSm9pbi5hZGRFdmVudExpc3RlbmVyKCdjbGljaycsIGZ1bmN0aW9uKCl7XG4gICAgaWYgKCEoUyAhPSBudWxsICYmIFMuaXNPcGVuKSkge1xuICAgICAgcmV0dXJuIGRlYnVnKFwiZXJyb3I6IG5vdCBjb25uZWN0ZWQgeWV0XCIpO1xuICAgIH1cbiAgICBpZiAoam9pbmVkKSB7XG4gICAgICByZXR1cm4gZGVidWcoXCJlcnJvcjogYWxyZWFkeSBqb2luZWRcIik7XG4gICAgfVxuICAgIGlmICgoZ2FtZUlkID0gaW5wdXRHYW1lSWQudmFsdWUudHJpbSgpKS5sZW5ndGggPT09IDApIHtcbiAgICAgIHJldHVybiBkZWJ1ZyhcImVtcHR5IGdhbWUgaWRcIik7XG4gICAgfVxuICAgIHBsYXllck5hbWUgPSBpbnB1dE5hbWUudmFsdWUudHJpbSgpO1xuICAgIEcgPSBQUkVGSVggKyBcIi5nYW1lLlwiICsgZ2FtZUlkO1xuICAgIHJldHVybiBzdWJzY3JpYmUoKS50aGVuKGZ1bmN0aW9uKCl7XG4gICAgICBkZWJ1ZyhcImpvaW5pbmcuLi5cIik7XG4gICAgICByZXR1cm4gUy5jYWxsKEcgKyBcIi5qb2luXCIsIFtwbGF5ZXJOYW1lXSk7XG4gICAgfSkudGhlbihmdW5jdGlvbih0b2tlbil7XG4gICAgICBkZWJ1ZyhcIiAgam9pbmVkLiBwbGF5ZXIgdG9rZW46IFwiICsgdG9rZW4pO1xuICAgICAgcGxheWVyVG9rZW4gPSB0b2tlbjtcbiAgICAgIHJldHVybiB1cGRhdGVKb2luZWQodHJ1ZSk7XG4gICAgfSlbJ2NhdGNoJ10oZnVuY3Rpb24oZXJyKXtcbiAgICAgIGRlYnVnKFwiICBlcnJvcjogXCIgKyBlcnIpO1xuICAgICAgY29uc29sZS5lcnJvcihlcnIpO1xuICAgICAgcmV0dXJuIHVuU3Vic2NyaWJlKCk7XG4gICAgfSk7XG4gIH0pO1xuICBidG5MZWF2ZS5hZGRFdmVudExpc3RlbmVyKCdjbGljaycsIGZ1bmN0aW9uKCl7XG4gICAgaWYgKCEoUyAhPSBudWxsICYmIFMuaXNPcGVuKSkge1xuICAgICAgcmV0dXJuIGRlYnVnKFwiZXJyb3I6IG5vdCBjb25uZWN0ZWQgeWV0XCIpO1xuICAgIH1cbiAgICBpZiAoIWpvaW5lZCkge1xuICAgICAgcmV0dXJuIGRlYnVnKFwiZXJyb3I6IG5vdCBqb2luZWRcIik7XG4gICAgfVxuICAgIGRlYnVnKFwibGVhdmluZy4uLlwiKTtcbiAgICByZXR1cm4gUy5jYWxsKEcgKyBcIi5sZWF2ZVwiLCBbcGxheWVyVG9rZW5dKS50aGVuKGZ1bmN0aW9uKCl7XG4gICAgICBkZWJ1ZyhcIiAgbGVhdmVkLlwiKTtcbiAgICAgIHBsYXllclRva2VuID0gbnVsbDtcbiAgICAgIHVwZGF0ZUpvaW5lZChmYWxzZSk7XG4gICAgICByZXR1cm4gdW5TdWJzY3JpYmUoKTtcbiAgICB9KVsnY2F0Y2gnXShmdW5jdGlvbihlcnIpe1xuICAgICAgZGVidWcoXCIgIGVycm9yOiBcIiArIGVycik7XG4gICAgICByZXR1cm4gY29uc29sZS5lcnJvcihlcnIpO1xuICAgIH0pO1xuICB9KTtcbiAgc3Vic2NyaXB0aW9uID0gbnVsbDtcbiAgZnVuY3Rpb24gc3Vic2NyaWJlKCl7XG4gICAgcmV0dXJuIFMuc3Vic2NyaWJlKEcsIGhhbmRsZXIpLnRoZW4oZnVuY3Rpb24oaXQpe1xuICAgICAgcmV0dXJuIHN1YnNjcmlwdGlvbiA9IGl0O1xuICAgIH0pO1xuICB9XG4gIGZ1bmN0aW9uIHVuU3Vic2NyaWJlKCl7XG4gICAgaWYgKHN1YnNjcmlwdGlvbikge1xuICAgICAgcmV0dXJuIFMudW5zdWJzY3JpYmUoc3Vic2NyaXB0aW9uKTtcbiAgICB9XG4gIH1cbiAgZnVuY3Rpb24gaGFuZGxlcihhcmdzKXtcbiAgICB2YXIgdHlwZSwgZGV0YWlscztcbiAgICB0eXBlID0gYXJnc1swXSwgZGV0YWlscyA9IGFyZ3NbMV07XG4gICAgc3dpdGNoICh0eXBlKSB7XG4gICAgY2FzZSAnam9pbic6XG4gICAgICByZXR1cm4gZGVidWcoXCJwbGF5ZXIgXCIgKyBkZXRhaWxzICsgXCIgaGFzIGpvaW5lZFwiKTtcbiAgICBjYXNlICdsZWF2ZSc6XG4gICAgICByZXR1cm4gZGVidWcoXCJwbGF5ZXIgXCIgKyBkZXRhaWxzICsgXCIgaGFzIGxlYXZlZFwiKTtcbiAgICBjYXNlICdzdGFydCc6XG4gICAgICBwbGF5ZXJOYW1lcyA9IGRldGFpbHM7XG4gICAgICBwbGF5ZXJTZWF0ID0gcGxheWVyTmFtZXMuaW5kZXhPZihwbGF5ZXJOYW1lKTtcbiAgICAgIGlmIChwbGF5ZXJTZWF0ID09PSAtMSkge1xuICAgICAgICBkZWJ1ZyhcImdhbWUgc3RhcnRlZCB3aXRob3V0IHlvdSAoV1RGPylcIik7XG4gICAgICAgIHJldHVybiBjb25uLmNsb3NlKCk7XG4gICAgICB9IGVsc2Uge1xuICAgICAgICByZXR1cm4gc3RhcnRHYW1lKCk7XG4gICAgICB9XG4gICAgfVxuICB9XG4gIGZ1bmN0aW9uIHN0YXJ0R2FtZSgpe1xuICAgIHZhciBhcmdzLCBzO1xuICAgIGNvbm4uY2xvc2UoKTtcbiAgICBhcmdzID0ge1xuICAgICAgZ2FtZUlkOiBnYW1lSWQsXG4gICAgICBwbGF5ZXJOYW1lczogcGxheWVyTmFtZXMsXG4gICAgICBwbGF5ZXJTZWF0OiBwbGF5ZXJTZWF0LFxuICAgICAgcGxheWVyVG9rZW46IHBsYXllclRva2VuXG4gICAgfTtcbiAgICBzID0gZW5jb2RlVVJJQ29tcG9uZW50KEpTT04uc3RyaW5naWZ5KGFyZ3MpKTtcbiAgICByZXR1cm4gd2luZG93LmxvY2F0aW9uID0gJ2dhbWUuaHRtbCMnICsgcztcbiAgfVxufSkuY2FsbCh0aGlzKTtcbiJdfQ==
